### ISSUE TITLE
Set up continuous integration (CI) using GitHub Actions

### ISSUE THREAD

**Issue by danieldietrich** [langium/langium#2]
## Story

As a committer I want to ensure that PRs don't break the code base, including tests.

## Acceptance criteria

* [ ] We use [GitHub Actions](https://docs.github.com/en/actions) to **build** and **test** the projects on **push** or **PR** to branch **main**.

The triggers could look like this:

```yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```

---

## Dependencies

Probably we need to update our GitHub plan until we will be able to use GitHub Actions.
